/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.costa.mh.gui;

import com.costa.mh.biz.MaquinaHelado;
import com.costa.mh.dao.pojo.Helado;
import com.costa.mh.exceptions.NotEnoughMoneyException;
import com.costa.mh.exceptions.NotValidPositionException;
import com.costa.mh.exceptions.QuantityExceededException;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dev
 */
public class ExecGUI extends javax.swing.JFrame {

    /**
     * Creates new form ExecGUI
     */
    public ExecGUI() {
        FlatLightLaf.setup();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        labelExceptions = new javax.swing.JLabel();
        labelPresentacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHelados = new javax.swing.JTable();
        botonIntroMoneda = new javax.swing.JButton();
        labelDinero = new javax.swing.JLabel();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelPosHelado = new javax.swing.JLabel();
        pedirHelado = new javax.swing.JButton();
        getCambio = new javax.swing.JButton();
        labelHelado = new javax.swing.JTextField();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuVentas = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelExceptions.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 18)); // NOI18N

        labelPresentacion.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        labelPresentacion.setText("Máquina de Helados");

        tablaHelados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posición", "Helado", "Precio", "Tipo", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaHelados.setRowHeight(30);
        tablaHelados.getTableHeader().setReorderingAllowed(false);
        tablaHelados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaHeladosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaHelados);
        if (tablaHelados.getColumnModel().getColumnCount() > 0) {
            tablaHelados.getColumnModel().getColumn(0).setResizable(false);
            tablaHelados.getColumnModel().getColumn(1).setResizable(false);
            tablaHelados.getColumnModel().getColumn(2).setResizable(false);
            tablaHelados.getColumnModel().getColumn(3).setResizable(false);
            tablaHelados.getColumnModel().getColumn(4).setResizable(false);
        }

        botonIntroMoneda.setText("Introducir monedas");
        botonIntroMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIntroMonedaActionPerformed(evt);
            }
        });

        labelDinero.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 18)); // NOI18N
        labelDinero.setText("0 €");

        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });

        botonBorrar.setText("<");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        labelPosHelado.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 18)); // NOI18N

        pedirHelado.setText("Pedir helado");
        pedirHelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirHeladoActionPerformed(evt);
            }
        });

        getCambio.setText("Cambio");
        getCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getCambioActionPerformed(evt);
            }
        });

        labelHelado.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 18)); // NOI18N

        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });

        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });

        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });

        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });

        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });

        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });

        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        jMenu1.setText("Menú");

        menuVentas.setText("Ventas totales");
        menuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentasActionPerformed(evt);
            }
        });
        jMenu1.add(menuVentas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(labelPresentacion))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(527, 527, 527)
                        .addComponent(labelPosHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(labelDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(botonIntroMoneda)
                .addGap(12, 12, 12)
                .addComponent(getCambio)
                .addGap(6, 6, 6)
                .addComponent(pedirHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelExceptions, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labelHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(boton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton2)
                .addGap(6, 6, 6)
                .addComponent(boton3))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(boton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton5)
                .addGap(6, 6, 6)
                .addComponent(boton6)
                .addGap(12, 12, 12)
                .addComponent(botonBorrar))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(boton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton0)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton8)
                        .addGap(6, 6, 6)
                        .addComponent(boton9))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelPresentacion)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPosHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonIntroMoneda)
                            .addComponent(getCambio)
                            .addComponent(pedirHelado))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelExceptions)
                    .addComponent(labelHelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton1)
                            .addComponent(boton2)
                            .addComponent(boton3))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton4)
                    .addComponent(boton5)
                    .addComponent(boton6)
                    .addComponent(botonBorrar))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton7)
                    .addComponent(boton8)
                    .addComponent(boton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton0)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIntroMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIntroMonedaActionPerformed
        ModalIntroCoins modalMonedas = new ModalIntroCoins(this, true);
        modalMonedas.setVisible(true);
        refrescarLabelDinero();
    }//GEN-LAST:event_botonIntroMonedaActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        this.escribirEnPosicion("1");

    }//GEN-LAST:event_boton1ActionPerformed


    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        this.escribirEnPosicion("2");

    }//GEN-LAST:event_boton2ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        this.escribirEnPosicion("0");

    }//GEN-LAST:event_boton0ActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        if (this.labelHelado.getText().length() != 0) {
            this.labelHelado.setText(this.labelHelado.getText().substring(0, this.labelHelado.getText().length() - 1));
            this.posHelado = this.posHelado.substring(0, this.labelHelado.getText().length());
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        refrescar();
    }//GEN-LAST:event_formWindowOpened

    private void tablaHeladosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaHeladosMouseClicked
        int fila = this.tablaHelados.getSelectedRow();
        escribirEnPosicionTablaHelados((String) this.tablaHelados.getValueAt(fila, 0));

    }//GEN-LAST:event_tablaHeladosMouseClicked

    private void getCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getCambioActionPerformed
        ModalChange modalChange = new ModalChange(this, true);
        modalChange.setVisible(true);
        refrescarLabelDinero();
    }//GEN-LAST:event_getCambioActionPerformed

    private void pedirHeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirHeladoActionPerformed
        try {
            this.h = this.mh.pedirHelado(this.posHelado);
            this.labelExceptions.setText("Ha comprado el helado: " + h.getNombre());
        } catch (NotEnoughMoneyException | NotValidPositionException | QuantityExceededException e) {
            this.labelExceptions.setText(e.getMessage());
        } catch (Exception e) {
            this.labelExceptions.setText("Ha ocurrido un error inesperado.");
        }
        refrescar();
        refrescarLabelDinero();
    }//GEN-LAST:event_pedirHeladoActionPerformed

    private void menuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentasActionPerformed
        ModalTotalSales ventas = new ModalTotalSales(this, true);
        ventas.setVisible(true);

    }//GEN-LAST:event_menuVentasActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (this.mh.getMonedero() != 0) {
            ModalChange modalChange = new ModalChange(this, true);
            modalChange.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        this.escribirEnPosicion("8");
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        this.escribirEnPosicion("7");
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        this.escribirEnPosicion("9");
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        this.escribirEnPosicion("6");
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        this.escribirEnPosicion("5");
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        this.escribirEnPosicion("4");
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        this.escribirEnPosicion("3");
    }//GEN-LAST:event_boton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExecGUI().setVisible(true);
            }
        });
    }

    public void refrescar() {
        DefaultTableModel m = (DefaultTableModel) this.tablaHelados.getModel();
        ArrayList<Helado> helados = this.mh.heladoToList();
        m.setNumRows(0);
        for (Helado helado : helados) {
            Object[] o = {helado.getPosicion(), helado.getNombre(), helado.getPrecio() + "€", helado.getTipo(), helado.getCantidad()};
            m.addRow(o);
        }
    }

    public void refrescarLabelDinero() {
        this.labelDinero.setText(this.mh.getMonedero() + "€");
    }

    public void escribirEnPosicion(String s) {
        if (this.labelHelado.getText().length() < 2) {
            this.labelHelado.setText(this.labelHelado.getText() + s);
            this.posHelado = this.posHelado + s;
        }
    }

    private void escribirEnPosicionTablaHelados(String s) {
        this.labelHelado.setText(s);
        this.posHelado = s;
    }

    private String posHelado = "";
    public Helado h;
    public MaquinaHelado mh = new MaquinaHelado();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonIntroMoneda;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton getCambio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelDinero;
    private javax.swing.JLabel labelExceptions;
    private javax.swing.JTextField labelHelado;
    private javax.swing.JLabel labelPosHelado;
    private javax.swing.JLabel labelPresentacion;
    private javax.swing.JMenuItem menuVentas;
    private javax.swing.JButton pedirHelado;
    private javax.swing.JTable tablaHelados;
    // End of variables declaration//GEN-END:variables

}
