/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.costa.mh.gui;

import com.costa.mh.biz.MaquinaHelado;
import com.costa.mh.dao.pojo.Helado;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dev
 */
public class ExecGUI extends javax.swing.JFrame {

    /**
     * Creates new form ExecGUI
     */
    public ExecGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        labelPresentacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHelados = new javax.swing.JTable();
        botonIntroMoneda = new javax.swing.JButton();
        labelDinero = new javax.swing.JLabel();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelPosHelado = new javax.swing.JLabel();
        pedirHelado = new javax.swing.JButton();
        getCambio = new javax.swing.JButton();
        labelHelado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuVentas = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelPresentacion.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        labelPresentacion.setText("Máquina de Helados");

        tablaHelados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posición", "Helado", "Precio", "Tipo", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaHelados.setRowHeight(30);
        tablaHelados.getTableHeader().setReorderingAllowed(false);
        tablaHelados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaHeladosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaHelados);
        if (tablaHelados.getColumnModel().getColumnCount() > 0) {
            tablaHelados.getColumnModel().getColumn(0).setResizable(false);
            tablaHelados.getColumnModel().getColumn(1).setResizable(false);
            tablaHelados.getColumnModel().getColumn(2).setResizable(false);
            tablaHelados.getColumnModel().getColumn(3).setResizable(false);
            tablaHelados.getColumnModel().getColumn(4).setResizable(false);
        }

        botonIntroMoneda.setText("Introducir monedas");
        botonIntroMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIntroMonedaActionPerformed(evt);
            }
        });

        labelDinero.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 18)); // NOI18N
        labelDinero.setText("0 €");

        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });

        botonBorrar.setText("<");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        labelPosHelado.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 18)); // NOI18N

        pedirHelado.setText("Pedir helado");
        pedirHelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirHeladoActionPerformed(evt);
            }
        });

        getCambio.setText("Cambio");
        getCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getCambioActionPerformed(evt);
            }
        });

        labelHelado.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 18)); // NOI18N

        jLabel2.setText("jLabel2");

        jMenu1.setText("Menú");

        menuVentas.setText("Ventas totales");
        menuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentasActionPerformed(evt);
            }
        });
        jMenu1.add(menuVentas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(labelDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonIntroMoneda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(getCambio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pedirHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelPosHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(boton0)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boton2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonBorrar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(labelPresentacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelPresentacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonIntroMoneda)
                            .addComponent(labelDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getCambio)
                            .addComponent(pedirHelado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton0)
                            .addComponent(boton1)
                            .addComponent(boton2)
                            .addComponent(botonBorrar)
                            .addComponent(labelHelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPosHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIntroMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIntroMonedaActionPerformed
        ModalIntroCoins modalMonedas = new ModalIntroCoins(this, true);
        modalMonedas.setVisible(true);
        refrescarLabelDinero();
    }//GEN-LAST:event_botonIntroMonedaActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        this.escribirEnPosicion("1");

    }//GEN-LAST:event_boton1ActionPerformed


    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        this.escribirEnPosicion("2");

    }//GEN-LAST:event_boton2ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        this.escribirEnPosicion("0");

    }//GEN-LAST:event_boton0ActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        if (this.labelHelado.getText().length() != 0) {
            this.labelHelado.setText(this.labelHelado.getText().substring(0, this.labelHelado.getText().length() - 1));
            this.posHelado = this.posHelado.substring(0, this.labelHelado.getText().length());
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        refrescar();
    }//GEN-LAST:event_formWindowOpened

    private void tablaHeladosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaHeladosMouseClicked
        int fila = this.tablaHelados.getSelectedRow();
        escribirEnPosicionTablaHelados((String) this.tablaHelados.getValueAt(fila, 0));
       
    }//GEN-LAST:event_tablaHeladosMouseClicked

    private void getCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getCambioActionPerformed
        ModalChange modalChange = new ModalChange(this, true);
        modalChange.setVisible(true);
        refrescarLabelDinero();
    }//GEN-LAST:event_getCambioActionPerformed

    private void pedirHeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirHeladoActionPerformed
        try {
            this.h  = this.mh.pedirHelado(this.posHelado);
            ModalHeladoComprado mhc = new ModalHeladoComprado(this, true);
            mhc.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ExecGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        refrescar();
        refrescarLabelDinero();
    }//GEN-LAST:event_pedirHeladoActionPerformed

    private void menuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentasActionPerformed
        ModalTotalSales ventas = new ModalTotalSales(this, true);
        ventas.setVisible(true);

    }//GEN-LAST:event_menuVentasActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      // Nothing
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         if (this.mh.getMonedero() != 0) {
            ModalChange modalChange = new ModalChange(this, true);
            modalChange.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExecGUI().setVisible(true);
            }
        });
    }

    
      

    public void refrescar() {
        DefaultTableModel m = (DefaultTableModel) this.tablaHelados.getModel();
        ArrayList<Helado> helados = this.mh.heladoToList();
        m.setNumRows(0);
        for (Helado helado : helados) {
            Object[] o = {helado.getPosicion(), helado.getNombre(), helado.getPrecio() + "€", helado.getTipo(), helado.getCantidad()};
            m.addRow(o);
        }
    }

    public void refrescarLabelDinero() {
        this.labelDinero.setText(this.mh.getMonedero() + "€");
    }

    public void escribirEnPosicion(String s) {
        if (this.labelHelado.getText().length() < 2) {
            this.labelHelado.setText(this.labelHelado.getText() + s);
            this.posHelado = this.posHelado + s;
        }
    }
    
    
    private void escribirEnPosicionTablaHelados(String s) {
        this.labelHelado.setText(s);
        this.posHelado = s;
    }

    private String posHelado = "";
    public Helado h;
    public MaquinaHelado mh = new MaquinaHelado();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonIntroMoneda;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton getCambio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelDinero;
    private javax.swing.JTextField labelHelado;
    private javax.swing.JLabel labelPosHelado;
    private javax.swing.JLabel labelPresentacion;
    private javax.swing.JMenuItem menuVentas;
    private javax.swing.JButton pedirHelado;
    private javax.swing.JTable tablaHelados;
    // End of variables declaration//GEN-END:variables

}
