/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.costa.mh.gui;

import com.costa.mh.biz.MaquinaHelado;

/**
 *
 * @author dev
 */
public class ModalIntroCoins extends javax.swing.JDialog {

    /**
     * Creates new form ModalIntroCoins
     *
     * @param parent
     * @param modal
     */
    public ModalIntroCoins(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.padre = (ExecGUI) parent;
        this.labelDineroIntroducido.setText(this.padre.mh.getMonedero() + "€");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelDineroIntroducido = new javax.swing.JLabel();
        diezCents = new javax.swing.JButton();
        veinteCents = new javax.swing.JButton();
        cincuentaCents = new javax.swing.JButton();
        euro = new javax.swing.JButton();
        dosEuros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Insert Coins");
        jLabel1.setToolTipText("");

        labelDineroIntroducido.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 24)); // NOI18N
        labelDineroIntroducido.setText("0 €");
        labelDineroIntroducido.setToolTipText("");
        labelDineroIntroducido.setAlignmentY(0.0F);

        diezCents.setText("0.10€");
        diezCents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diezCentsActionPerformed(evt);
            }
        });

        veinteCents.setText("0.20€");
        veinteCents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veinteCentsActionPerformed(evt);
            }
        });

        cincuentaCents.setText("0.50€");
        cincuentaCents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincuentaCentsActionPerformed(evt);
            }
        });

        euro.setText("1€");
        euro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euroActionPerformed(evt);
            }
        });

        dosEuros.setText("2€");
        dosEuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosEurosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(euro)
                        .addGap(18, 18, 18)
                        .addComponent(dosEuros))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(diezCents)
                                .addGap(18, 18, 18)
                                .addComponent(veinteCents))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelDineroIntroducido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(cincuentaCents)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDineroIntroducido)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diezCents)
                    .addComponent(veinteCents)
                    .addComponent(cincuentaCents))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(euro)
                    .addComponent(dosEuros))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diezCentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diezCentsActionPerformed
        this.padre.mh.setMonedero(this.padre.mh.getMonedero() + 0.10);
        this.labelDineroIntroducido.setText(this.padre.mh.getMonedero() + "€");
    }//GEN-LAST:event_diezCentsActionPerformed

    private void veinteCentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veinteCentsActionPerformed
        this.padre.mh.setMonedero(this.padre.mh.getMonedero() + 0.20);
        this.labelDineroIntroducido.setText(this.padre.mh.getMonedero() + "€");    }//GEN-LAST:event_veinteCentsActionPerformed

    private void cincuentaCentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincuentaCentsActionPerformed

        this.padre.mh.setMonedero(this.padre.mh.getMonedero() + 0.50);
        this.labelDineroIntroducido.setText(this.padre.mh.getMonedero() + "€");
    }//GEN-LAST:event_cincuentaCentsActionPerformed

    private void euroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euroActionPerformed

        this.padre.mh.setMonedero(this.padre.mh.getMonedero() + 1);
        this.labelDineroIntroducido.setText(this.padre.mh.getMonedero() + "€");
    }//GEN-LAST:event_euroActionPerformed

    private void dosEurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosEurosActionPerformed
         this.padre.mh.setMonedero(this.padre.mh.getMonedero() + 2);
        this.labelDineroIntroducido.setText(this.padre.mh.getMonedero() + "€");
    }//GEN-LAST:event_dosEurosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalIntroCoins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalIntroCoins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalIntroCoins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalIntroCoins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ModalIntroCoins dialog = new ModalIntroCoins(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private ExecGUI padre;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cincuentaCents;
    private javax.swing.JButton diezCents;
    private javax.swing.JButton dosEuros;
    private javax.swing.JButton euro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDineroIntroducido;
    private javax.swing.JButton veinteCents;
    // End of variables declaration//GEN-END:variables
}
